patterns:
  - "^az ([a-z-]+ )+list($| )"
  - "^az ([a-z-]+ )+list-[a-z-]+($| )"
  - "^az ([a-z-]+ )+show($| )"
  - "^az ([a-z-]+ )+get-[a-z-]+($| )"
  - "^az account show($| )"
  - "^az account list($| )"
  - "^az account list-locations($| )"
  - "^az ([a-z-]+ )+check-[a-z-]+($| )"
  - "^az ([a-z-]+ )+describe($| )"
  - "^az ([a-z-]+ )+query($| )"
